coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

ignore:
  - "gen/**"
  - "**/*.pb.go"
  - "**/platform/darwin/**"
  - "**/platform/linux/**"
  - "**/platform/windows/**"
  - "cmd/peridotd/main.go"
  - "cmd/peridot/main.go"
